### PR TITLE
Custom reverts

### LINKED ISSUE #125: Fetch revert reason for the failed transactions
## Problem

Currently, for failed transactions reverted with custom errors, skaled returns the generic revert message:

> EVM revert instruction without description message

Blockscout then displays the same generic message as the revert reason.

Image

However, the actual revert reason can be retrieved by running `eth_call` with the same call parameters as the failed transaction (same `from`, `to`, `data`, `value`, and block number).

If transaction is failed with `EVM revert...` and **the contract is verified** we need to:
1. Make eth_call with the transaction data
2. If the response contains `data` field and contract is verified, we need to decode it
3. Write the decoded value in the DB
4. Show it on the UI

**OR**

1. Explore Blockscout options to resolve this problem 

## Decoding

By executing `eth_call` with the same parameters as the failed transaction, the node returns an error response that includes revert data in the `error.data` field.

This field contains the actual revert payload (custom error selector and encoded arguments), even though the message remains the generic:
```
>>> curl http://10.3.155.162:10003/ -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"eth_call","params":[{"from":"0xce11987ccb652688d3dc52172e3dd34e0c79318a","to":"0xf668f8deaa9f91ac08473062d97257f001ce10a1","data":"0x40a281dd56b7eab6bf3ace9ca5ff5862cdf3a25f94f285acfa2675eba4e3829b2241f12eed78312fefe72a94d6354d9a29e0c19afeeeb2e60b07b94828293e21318db622","value":"0xf4240"},"0xf40e"],"id":1}'

<<< {"error":{"code":3,"data":"0x3ebbc337000000000000000000000000000000000000000000000000000000e8d4a5100000000000000000000000000000000000000000000000000000000000000f4240","message":"EVM revert instruction without description message"},"id":1,"jsonrpc":"2.0"}
```

> EVM revert instruction without description message

If the contract is verified and the ABI is available, the revert payload can be decoded to reveal the real error.

In this case, the payload decodes to:

**InsufficientEth(required=3906250000, available=1000000)**

### PR DESCRIPTION
**Pull request by yavrsky**
Provided feature enables support of custom revert reasons on transaction details page.
Closes #125

### CODE REVIEW

File: apps/explorer/lib/explorer/chain.ex [hunk 1]
```diff
@@ -120,8 +120,8 @@ defmodule Explorer.Chain do
   # Geth-like node
   @revert_msg_prefix_5 "execution reverted: "
   @revert_msg_prefix_6_empty "execution reverted"
+  @revert_msg_prefix_7_skale "EVM revert instruction without description message"
 
-  @burn_address_hash_str "0x0000000000000000000000000000000000000000"
```
Comment (DmytroNazarenko) [inline apps/explorer/lib/explorer/chain.ex:124]: Could you clarify why this constant was removed?

File: apps/explorer/lib/explorer/smart_contract/solidity/verifier.ex [hunk 2]
```diff
@@ -495,11 +495,12 @@ defmodule Explorer.SmartContract.Solidity.Verifier do
...
-    ["", rest_blockchain] = String.split(creation_code, trimmed_bytecode)
-    ["", rest_generated] = String.split(generated_bytecode, trimmed_bytecode)
-    ConstructorArguments.experimental_find_constructor_args(rest_blockchain, rest_generated, abi)
-  end
+  # Experimental/unfinished function - commented out due to undefined ConstructorArguments module
+  # defp try_to_verify_with_unknown_constructor_args(creation_code, generated_bytecode, trimmed_bytecode, abi) do
+  #   ["", rest_blockchain] = String.split(creation_code, trimmed_bytecode)
+  #   ["", rest_generated] = String.split(generated_bytecode, trimmed_bytecode)
+  #   ConstructorArguments.experimental_find_constructor_args(rest_blockchain, rest_generated, abi)
+  # end
```
Comment (DmytroNazarenko) [inline apps/explorer/lib/explorer/smart_contract/solidity/verifier.ex]: Why this code was commented out? Seems like we are not using it in this PR

**Review by DmytroNazarenko — COMMENTED** [review]
Do we need any migration procedure to update already running blockscouts?

File: apps/explorer/lib/explorer/chain.ex (hunk 1 above)
Comment (yavrsky) [reply apps/explorer/lib/explorer/chain.ex:124]: it's not used anywhere

File: apps/explorer/lib/explorer/smart_contract/solidity/verifier.ex (hunk 2 above)
Comment (yavrsky) [reply apps/explorer/lib/explorer/smart_contract/solidity/verifier.ex]: It raises a warning that such function is not used anywhere, probably it something experimental or unfinished by blockscout core team

**Review by DmytroNazarenko — APPROVED** [review]
